name: books
description: Organize your books and enhance reading experience.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  http: ^0.13.3
  localstorage: ^4.0.0+1
  just_debounce_it: ^4.0.0+2
  flutter_markdown: ^0.6.1
  url_launcher: ^6.0.3
  animated_text: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Kingthings
      fonts:
        - asset: assets/Kingthings-Trypewriter-2.ttf
       